### ISSUE TITLE
[FEATURE REQUEST] Implement CI pipeline for GEOS-Chem classic wrapper repository 

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCClassic#2]
Currently we test GEOS-Chem Classic with Azure. This will no longer work with the release of 13.0.0 since GEOS-Chem will be built inside of GEOS-Chem-Classic (this new repository). We will need to update the CI pipeline prior to that transition.

**Comment by LiamBindle** [comment]
I think #4 should get the `.ci-pipeline` files to work. One of the things #4 includes is the ability to build without a run directory (by doing `-DRUNDIR=IGNORE` and `-DRUNDIR_SIM=standard`. This is what the CI pipelines did to avoid having to create run directories (for the bootstrapping)--it should be fixed now

**Comment by msulprizio** [comment]
This capability was added by @yantosca in the dev/13.0.0 branch.
