### ISSUE TITLE
Errors while running the benchmark 1-month simulation 

### ISSUE THREAD

**Issue by gouravsaha1995** [geoschem/GCClassic#45]
### Name and Institution (Required)

Name: Gourav Saha
Institution: IIT Delhi

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/GCClassic/issues)

### Description of your issue or question

After downloading all the necessary files for the benchmark 1 month simulation-20190701 to 20190801, this error is being shown:

HEMCO: Opening ./Restarts/GEOSChem.Restart.20190701_0000z.nc4

HEMCO ERROR: Cannot find field SPC_BUTDI. Please check variable name in the co
 nfig. file

HEMCO ERROR: Error encountered in routine HCOIO_Read!

HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_BUTD
 I
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

HEMCO ERROR: Error in called ReadList_Fill (7) from HEMCO ReadList_Read
 --> L
 OCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
additional error messages!
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0

This error can indicate a missing file. Please check the HEMCO log file for
additional error messages!

STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===================================================

**Comment by msulprizio** [comment]
This is a known issue - see https://github.com/geoschem/geos-chem/pull/1986. It has been resolved in 14.2.2 by updating the sample restart file - see https://github.com/geoschem/geos-chem/pull/1989.
